services:
  db:
    image: postgres:16-alpine
    container_name: tablica_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tablica
    ports:
      - "5432:5432"
    volumes:
      - tablica_pgdata:/var/lib/postgresql/data

volumes:
  tablica_pgdata:
